export const ErrorCodes = {
  // Auth (1xxx)
  UNAUTHORIZED: 'AUTH_1001',
  INVALID_TOKEN: 'AUTH_1002',
  TOKEN_EXPIRED: 'AUTH_1003',
  FORBIDDEN: 'AUTH_1004',

  // Validation (2xxx)
  VALIDATION_ERROR: 'VAL_2001',

  // Resource (3xxx)
  NOT_FOUND: 'RES_3001',
  CONFLICT: 'RES_3002',
  BAD_REQUEST: 'RES_3003',

  // Rate Limit (4xxx)
  RATE_LIMITED: 'RATE_4001',

  // Server (5xxx)
  INTERNAL_ERROR: 'SRV_5001',
  DATABASE_ERROR: 'SRV_5002',

  // Pricing (6xxx)
  EXTRA_CAPACITY_EXCEEDED: 'PRC_6001',
  PRICE_MISMATCH: 'PRC_6002',
  EXTRA_NOT_AVAILABLE: 'PRC_6003',
  INVALID_SPONSORSHIP_CODE: 'PRC_6004',
  PRICING_NOT_FOUND: 'PRC_6005',

  // Access (7xxx)
  ACCESS_NOT_FOUND: 'ACC_7001',
  ACCESS_CAPACITY_EXCEEDED: 'ACC_7002',
  ACCESS_TIME_CONFLICT: 'ACC_7004',
  ACCESS_PREREQUISITE_MISSING: 'ACC_7005',
  ACCESS_NOT_AVAILABLE: 'ACC_7006',
  ACCESS_CIRCULAR_DEPENDENCY: 'ACC_7007',
  ACCESS_HAS_REGISTRATIONS: 'ACC_7008',

  // Registration (8xxx)
  REGISTRATION_NOT_FOUND: 'REG_8001',
  REGISTRATION_ALREADY_EXISTS: 'REG_8002',
  REGISTRATION_CANCELLED: 'REG_8003',
  REGISTRATION_INVALID_STATUS: 'REG_8004',
  REGISTRATION_PAYMENT_REQUIRED: 'REG_8005',
  EVENT_CAPACITY_EXCEEDED: 'REG_8006',

  // Form Validation (9xxx)
  FORM_VALIDATION_ERROR: 'FRM_9001',
  FORM_FIELD_REQUIRED: 'FRM_9002',
  FORM_FIELD_INVALID_FORMAT: 'FRM_9003',
  FORM_FIELD_INVALID_TYPE: 'FRM_9004',
  FORM_FILE_TOO_LARGE: 'FRM_9005',
  FORM_FILE_INVALID_TYPE: 'FRM_9006',

  // Reports (10xxx)
  REPORT_GENERATION_FAILED: 'RPT_11001',
  EXPORT_FAILED: 'RPT_11002',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
